name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: textarea
    id: observed
    attributes:
      label: Description
      placeholder: |
        Describe the bug...
        **Describe step by step how to reproduce the bug:**
        ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - Not Decided
        - Low
        - Medium
        - High
        - Critical
      default: 0
    validations:
      required: false

  - type: checkboxes
    id: system
    attributes:
      label: System Environment
      description: Where was this observed?
      options:
        - label: Development
        - label: QA
        - label: Staging
        - label: Production
    validations:
      required: false
      
  - type: input
    id: version
    attributes:
      label: Software Version
      description: Provide version number or enter 'unknown'
      placeholder: v2.1.3, commit@abc123, or 'unknown'
    validations:
      required: false

  - type: checkboxes
    id: repository-selection
    attributes:
      label: Repository Selection Reminder
      description: Verify you have selected the correct repository before proceeding
      options:
        - label: "**I have verified this issue is being created in the CORRECT repository** the repository dropdown selection above**"
          required: true
    validations:
      required: true

  - type: checkboxes
    id: security_flags
    attributes:
      label: Security Assessment in Planning phase
      description: Check any security concerns (leave all unchecked if none apply)
      options:
        - label: Potential SQL injection vulnerability
        - label: Cross-Site Scripting (XSS) risk
        - label: Access control/authorization issue
        - label: Other security implications (explain below)

  - type: textarea
    id: security_assessment
    attributes:
      label: Security Assessment in Planning phase
      description: Are there any security implications to be aware of?
      placeholder: Describe any security considerations or enter 'None identified', 'Dont know', or 'Unknown'.
    validations:
      required: false

  - type: textarea
    id: internal_testing_report
    attributes:
      label: Internal Testing Report
      description: Describe the results of internal testing on QA.
      placeholder: Describe results of internal testing on QA
    validations:
      required: false

  - type: textarea
    id: customer_testing_report
    attributes:
      label: Customer Testing Report
      description: Describe the results of customer testing on Staging.
      placeholder: Describe results of customer testing on Staging.
    validations:
      required: false
