name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What is the bug?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: Step by step guide to reproduce bug
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this bug?
      options:
        - Not Decided
        - Low
        - Medium
        - High
        - Critical
      default: 0
    validations:
      required: false
