name: Feature Request
description: Request a new feature or enhancement
labels: [feature]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What should this feature do and why is it needed?
      placeholder: Clearly describe the proposed feature and its business value...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know when this feature is complete?
      placeholder: List one or more test or criterias to determine when the feature is complete
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Not Decided
        - Low
        - Medium
        - High
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: security_flags
    attributes:
      label: Security Assessment in Planning phase
      description: Check any security concerns (leave all unchecked if none apply)
      options:
        - label: Potential SQL injection vulnerability
        - label: Cross-Site Scripting (XSS) risk
        - label: Access control/authorization issue
        - label: Other security implications (explain below)

  - type: textarea
    id: security_assessment
    attributes:
      label: Security Assessment in Planning phase
      description: Are there any security implications to be aware of?
      placeholder: Describe any security considerations or enter 'None identified', 'Dont know', or 'Unknown'.
    validations:
      required: true

  - type: textarea
    id: internal_testing_report
    attributes:
      label: Internal Testing Report
      description: Describe the results of internal testing on QA.
      placeholder: Describe results of internal testing on QA
    validations:
      required: false

  - type: textarea
    id: customer_testing_report
    attributes:
      label: Customer Testing Report
      description: Describe the results of customer testing on Staging.
      placeholder: Describe results of customer testing on Staging.
    validations:
      required: false

