name: Debug Token Access Test
on:
  workflow_dispatch:

jobs:
  test_token:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID_AMI_PROJECT_AUTOMATION }}
          private-key: ${{ secrets.ISSUE_AUTOMATION }}
          owner: AMI-Global

      - name: Check Token Validity
        run: |
          curl -s -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user